<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "Новосибирск, транспортная компания, Байт Транзит, грузоперевозки, доставка грузов, перевозка грузов");
$APPLICATION->SetPageProperty("description", "Отправить резюме");
$APPLICATION->SetTitle("resume");

?> 
<br /><br><br>

<div style="width: 1140px; position: relative; left: 21%;">  <?$APPLICATION->IncludeComponent(
	"api:main.feedback", 
	".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"IBLOCK_TYPE" => "-",
		"IBLOCK_ID" => "",
		"INSTALL_IBLOCK" => "N",
		"IBLOCK_ELEMENT_ACTIVE" => "N",
		"DISABLE_SEND_MAIL" => "N",
		"REPLACE_FIELD_FROM" => "Y",
		"HIDE_FORM_AFTER_SEND" => "Y",
		"UNIQUE_FORM_ID" => "form5",
		"OK_TEXT" => "Ваше резюме успешно отправлено!",
		"OK_TEXT_AFTER" => "Мы свяжемся с Вами в самое ближайшее время.",
		"EMAIL_TO" => "belikova.ekaterina@sibtrans.ru",
		"BCC" => "osipovda@sibtrans.ru",
		"REDIRECT_PAGE" => "",
		"DISPLAY_FIELDS" => array(
		),
		"REQUIRED_FIELDS" => array(
		),
		"CUSTOM_FIELDS" => array(
			0 => "Ваше имя@input@type=text@name=NAME@value=@required@data-validation=[NAME]@data-validation-label=Ваше имя@tooltip-title=Ваше имя@sort=1",
			1 => "Ваш E-mail@input@type=text@name=EMAIL@required@data-validation=[EMAIL]@data-validation-label=Ваш E-mail@data-inputmask='alias': 'email'@sort=3",
			2 => "Номер телефона@input@type=text@name=PHONE@required@data-validation=[PHONE]@data-validation-label=Номер телефона@placeholder=+7(___) ___-____@data-inputmask='mask': '+7(999) 999-9999'@sort=3",
			3 => "Файлы@input@type=file@name=files@multiple@size=3@max=6@required",
			4 => "",
		),
		"ADMIN_EVENT_MESSAGE_ID" => array(
			0 => "37",
		),
		"USER_EVENT_MESSAGE_ID" => array(
			0 => "37",
		),
		"WRITE_ONLY_FILLED_VALUES" => "Y",
		"WRITE_MESS_DIV_STYLE" => "padding:10px;border-bottom:1px dashed #dadada;",
		"WRITE_MESS_DIV_STYLE_NAME" => "font-weight:bold;",
		"WRITE_MESS_DIV_STYLE_VALUE" => "background-color: brown;",
		"WRITE_MESS_FILDES_TABLE" => "N",
		"WRITE_MESS_TABLE_STYLE" => "font-family: Open Sans,Tahoma,Arial,sans-serif; font-size: 13px; border-collapse:collapse; border-spacing:0;",
		"WRITE_MESS_TABLE_STYLE_NAME" => "border: 1px solid #e0e0e0; border-left-color:#fff; padding: 5px 30px 5px 0px; vertical-align: middle;",
		"WRITE_MESS_TABLE_STYLE_VALUE" => "border: 1px solid #e0e0e0; border-right-color:#fff; padding: 5px 30px 5px 10px; vertical-align: middle;",
		"FORM_CLASS" => "",
		"TITLE_DISPLAY" => "Y",
		"FORM_TITLE" => "Отправить резюме",
		"FORM_TITLE_LEVEL" => "2",
		"FIELD_ERROR_MESS" => "#FIELD_NAME# обязятельно",
		"EMAIL_ERROR_MESS" => "Указанный E-mail некорректен",
		"DEFAULT_OPTION_TEXT" => "-- Выбрать --",
		"FORM_SUBMIT_CLASS" => "uk-button",
		"FORM_SUBMIT_VALUE" => "Отправить",
		"FORM_SUBMIT_STYLE" => "",
		"BUTTON_TEXT_BEFORE" => "",
		"FORM_TEXT_BEFORE" => "",
		"FORM_TEXT_AFTER" => "",
		"HIDE_FIELD_NAME" => "N",
		"HIDE_ASTERISK" => "N",
		"FORM_AUTOCOMPLETE" => "Y",
		"FIELD_BOX_SHADOW_ACTIVE" => "",
		"FIELD_BORDER_ACTIVE" => "",
		"FIELD_SIZE" => "default",
		"FIELD_NAME_POSITION" => "horizontal",
		"FORM_LABEL_TEXT_ALIGN" => "left",
		"FORM_LABEL_WIDTH" => "150",
		"FORM_FIELD_WIDTH" => "",
		"TEMPLATE_STYLE" => "uikit",
		"USE_HIDDEN_PROTECTION" => "N",
		"USE_CAPTCHA" => "Y",
		"INCLUDE_JQUERY" => "jquery2",
		"INCLUDE_CHOSEN" => "N",
		"INCLUDE_INPUTMASK" => "N",
		"INCLUDE_PLACEHOLDER" => "N",
		"INCLUDE_AUTOSIZE" => "N",
		"SCROLL_TO_FORM_IF_MESSAGES" => "N",
		"SCROLL_TO_FORM_SPEED" => "1000",
		"INCLUDE_VALIDATION" => "Y",
		"INCLUDE_ICHECK" => "N",
		"INCLUDE_TOOLTIPSTER" => "N",
		"BRANCH_ACTIVE" => "N",
		"SHOW_FILES" => "N",
		"UUID_LENGTH" => "10",
		"UUID_PREFIX" => "",
		"USE_YM_GOALS" => "N",
		"USER_AUTHOR_FIO" => "",
		"USER_AUTHOR_NAME" => "",
		"USER_AUTHOR_LAST_NAME" => "",
		"USER_AUTHOR_SECOND_NAME" => "",
		"USER_AUTHOR_EMAIL" => "",
		"USER_AUTHOR_PERSONAL_MOBILE" => "",
		"USER_AUTHOR_WORK_COMPANY" => "",
		"USER_AUTHOR_POSITION" => "",
		"USER_AUTHOR_PROFESSION" => "",
		"USER_AUTHOR_STATE" => "",
		"USER_AUTHOR_CITY" => "",
		"USER_AUTHOR_WORK_CITY" => "",
		"USER_AUTHOR_STREET" => "",
		"USER_AUTHOR_ADRESS" => "",
		"USER_AUTHOR_PERSONAL_PHONE" => "",
		"USER_AUTHOR_WORK_PHONE" => "",
		"USER_AUTHOR_FAX" => "",
		"USER_AUTHOR_MAILBOX" => "",
		"USER_AUTHOR_WORK_MAILBOX" => "",
		"USER_AUTHOR_SKYPE" => "",
		"USER_AUTHOR_ICQ" => "",
		"USER_AUTHOR_WWW" => "",
		"USER_AUTHOR_WORK_WWW" => "",
		"USER_AUTHOR_MESSAGE_THEME" => "",
		"USER_AUTHOR_MESSAGE" => "",
		"USER_AUTHOR_NOTES" => "",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"INCLUDE_CSSMODAL" => "N",
		"MODAL_WIDTH" => "",
		"MODAL_BUTTON_CLASS" => "uk-button uk-button-danger",
		"MODAL_BUTTON_HTML" => "Обратная связь",
		"MODAL_HEADER_HTML" => "Обратная связь",
		"MODAL_FOOTER_HTML" => "&copy; Форма обратной связи +",
		"SHOW_CSS_MODAL_AFTER_SEND" => "N",
		"SUBJECT" => "",
		"PAGE_TITLE" => "",
		"PAGE_URI" => "",
		"PAGE_URL" => "",
		"DIR_URL" => "",
		"DATETIME" => "",
		"USE_AGREEMENT" => "N",
		"SERVER_VARS" => array(
			0 => "",
			1 => "",
		),
		"REQUEST_VARS" => array(
			0 => "",
			1 => "",
		),
		"VALIDATION_MESSAGES" => array(
			0 => "'default':'\$ содержит ошибки'",
			1 => "'NOTEMPTY':'\$ обязательно'",
			2 => "'INTEGER':'\$ должно быть целым числом'",
			3 => "'NUMERIC':'\$ должно быть числом'",
			4 => "'MIXED':'\$ должно содержать буквы или цифры (без спец. символов).'",
			5 => "'NAME':'\$ неверного формата'",
			6 => "'NOSPACE':'\$ не должно содержать пробелы'",
			7 => "'TRIM':'\$ не должно начинаться или заканчиваться пробелом'",
			8 => "'DATE':'\$ содержит недопустимый формат YYYY-MM-DD'",
			9 => "'EMAIL':'\$ неверного формата'",
			10 => "'URL':'\$ неверного формата'",
			11 => "'PHONE':'\$ неверного формата'",
			12 => "'<':'\$ должно быть меньше % символов'",
			13 => "'<=':'\$ должно быть меньше или равно % символам'",
			14 => "'>':'\$ должно быть больше % символов.'",
			15 => "'>=':'\$ должно быть больше или равно % символам'",
			16 => "'==':'\$ должно быть равно % символам'",
			17 => "'!=':'\$ должно быть не равно % символам'",
			18 => "",
		)
	),
	false
);?>  </div> <br><br><br>

 <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>